name: Train and Deploy Model

on:
  issue_comment:
    types: [created, edited]
    condition: |
      contains(github.event.comment.body, '/train') ||
      contains(github.event.comment.body, '/deploy')
      && github.event.issue.user.login == 'turgut090'

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create trained directory
        run: |
          mkdir -p trained
          
      - name: Set environment variable
        run: |
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${{ github.event.comment.user.login }}" >> $GITHUB_ENV
          echo "URI=https://api.github.com" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV


      - name: Train model
        id: make_prediction
        if: |
          contains(github.event.comment.body, '/train')
        run: |
          mkdir -p docs
          args=($(echo "${{ github.event.comment.body }}" | awk -F' ' '{print $2, $3}'))
          python train_model.py "${args[0]}" "${args[1]}"

          
          
      - name: Save trained model
        if: |
          contains(github.event.comment.body, '/train')
        run: |
          mv docs/model.pkl docs/trained_model.pkl
          
      - name: Upload trained model artifact
        if: |
          contains(github.event.comment.body, '/train')
        uses: actions/upload-artifact@v3
        with:
          name: trained_model
          path: docs
          retention-days: 5
          
      - name: Download trained model artifact
        if: |
          contains(github.event.comment.body, '/deploy') 
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: workflow.yaml
          name: trained_model
          path: docs

      
      - name: Deploy model
        if: |
          (contains(github.event.comment.body, '/deploy')) 
        run: |
          python deploy.py

      - name: Commit files  
        if: |
          (contains(github.event.comment.body, '/deploy')) 
        run: |
          git config --global user.email "you@gmail.com"
          git config --local user.name  ${{ github.actor }}
          git add .
          git commit -m "new model is added"
          
      - name: Push changes  
        if: |
          (contains(github.event.comment.body, '/deploy'))
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
          
      - name: Deploy
        if: |
          (contains(github.event.comment.body, '/deploy'))
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

       